### ISSUE TITLE
数值分析勘误

### ISSUE THREAD

**Issue by stormckey** [JiepengLab/notebook#1]
感谢你的笔记，复习和打印出来都很好用！不过在阅读的过程中我感觉有注意到一些错误或者typo，如果有问题的话欢迎继续讨论。
不出意外的话截图左上角是有问题的地方，右侧会有目录的信息

**Comment by stormckey** [comment]
![701ea1ce334553cc09cb45999af4c4a5](https://github.com/JiepengLab/notebook/assets/109893671/6683b16b-49d7-4059-930b-77817c252c9d)

**Comment by stormckey** [comment]
![9fbfb18fa82f8c088ef68a8983d32c78](https://github.com/JiepengLab/notebook/assets/109893671/9bbee175-690e-44cc-a9df-61f5bd35d366)

两个赋值都没有写出来

**Comment by stormckey** [comment]
![ed30139a727e432bbc8691cc30568dcb](https://github.com/JiepengLab/notebook/assets/109893671/9a1d78e0-3ea2-4bb0-8374-38a604411e70)

感觉应该是A2 = M1A1 应该没有M直接乘在x上的

**Comment by stormckey** [comment]
![f4aa585ec6acd2a5b23e3ba5fb1d8ca3](https://github.com/JiepengLab/notebook/assets/109893671/93a769bb-446e-4fd8-b1fd-e2f29e85a575)

k应该不等于j 不然的话肯定是相等的

**Comment by stormckey** [comment]
![9414858d3f0ad1e40ef322c336958c92](https://github.com/JiepengLab/notebook/assets/109893671/f8a71b0c-3ca6-4799-95fa-4dc6c6317fd4)

取逆应该放在外面？

**Comment by stormckey** [comment]
![b9cce3666426f7cc8588ecb39393b077](https://github.com/JiepengLab/notebook/assets/109893671/b4c67d5a-729c-4ef6-bc40-982976b6db9b)

是不是没对齐 对角线应该都是2

**Comment by stormckey** [comment]
![9b6d912ed89e93410f5794ddcc044658](https://github.com/JiepengLab/notebook/assets/109893671/8f8dd97a-c5df-485d-aa3e-96bee6a19a90)

第一行感觉不是如果，没记错的话M就是代表二阶导

**Comment by stormckey** [comment]
![fa646280cbc43cf3be0301673bc42b60](https://github.com/JiepengLab/notebook/assets/109893671/fcf48219-bae4-44fc-9dc8-5b4b293089ee)

这个我不太确定，但是应该不是通过部分的点，而是要求尽可能接近每个点。
因为典型应用场景是数据点有噪声，严格要求通过其实并没有意义（因为就算通过了也不是精确的）

**Comment by stormckey** [comment]
![8c6440d4f4e0d63619e525cdfe95f215](https://github.com/JiepengLab/notebook/assets/109893671/a4de5dc5-7ad5-48dd-ad11-6d7fd6f5b534)

没有写无穷范数

**Comment by stormckey** [comment]
![54df4232dcaa612fb2fbb731c6d3c58d](https://github.com/JiepengLab/notebook/assets/109893671/5cab501f-dfca-4d8d-8d6c-e39f1c6808be)

应该是x^n

**Comment by stormckey** [comment]
![cc7ad42f37725bbf9ed80d959252f723](https://github.com/JiepengLab/notebook/assets/109893671/9e6efaad-1b4b-42b2-b9fa-0afcef3ae88c)

应该不是n阶逼近n阶，而是n-1阶逼近n阶

**Comment by stormckey** [comment]
![af643e47eaa8f0fcfbc5d0a931522a21](https://github.com/JiepengLab/notebook/assets/109893671/80fd392a-1aeb-4018-85ce-2df016e31c0d)

没渲染出来

**Comment by stormckey** [comment]
![0235111e2b4fe699831ae3a19774fbdb](https://github.com/JiepengLab/notebook/assets/109893671/7228f66a-afd5-4016-93bb-9728366fbd2f)

**Comment by stormckey** [comment]
![44fa2693fa591e5fc96c3c8f1f4f9951](https://github.com/JiepengLab/notebook/assets/109893671/ba6f6e9d-f0e3-4d8a-bb08-ce93bea78c24)

**Comment by stormckey** [comment]
大概就这些，最后还是感谢你的笔记！如果有问题欢迎继续讨论

**Comment by JiepengLab** [comment]
感谢勘误！个人水平有限，难免会出错ww，有什么问题欢迎随时指出~

### 第一个

> ![image](https://github.com/JiepengLab/notebook/assets/65861390/278d725c-dc95-4ffa-8c99-3692c10b3459)

上标问题我去找了找，发现是之前已经改过了的（可以刷新刷新~）
![image](https://github.com/JiepengLab/notebook/assets/65861390/f6c34620-5f61-4746-8711-6d00e4af404b)

### 第二个

> ![image](https://github.com/JiepengLab/notebook/assets/65861390/30d0e921-4ba2-4492-a091-054f140140e5)

已修正，感谢！
![image](https://github.com/JiepengLab/notebook/assets/65861390/6d2e2c8f-a271-499f-8c03-68b3e82ae2c1)

### 第三个

> ![image](https://github.com/JiepengLab/notebook/assets/65861390/3f7bd0bb-818b-4cc2-9f46-4ff57eb82914)

已修正，图中第二行的一般的之前也打错了。

![image](https://github.com/JiepengLab/notebook/assets/65861390/e75fcd16-22c7-4a27-b3ef-984b137baa7a)

### 第四个

>  ![image](https://github.com/JiepengLab/notebook/assets/65861390/9f96bfc2-bccb-42b9-be78-7a816c409759)

不严谨，已修正

![image](https://github.com/JiepengLab/notebook/assets/65861390/ced2d136-e366-44ee-8453-6056657a1e72)

### 第五个

> ![image](https://github.com/JiepengLab/notebook/assets/65861390/41238ba5-6d3f-444d-ad16-2dbde4277779)

确实，已修正。顺便更改了下表述

![image](https://github.com/JiepengLab/notebook/assets/65861390/7750a3c3-4230-4342-927c-69ee9c61bff7)

### 第六个

>  ![image](https://github.com/JiepengLab/notebook/assets/65861390/4384c9d9-cfe0-4057-b41b-eea19d1fc194)

确实多了一个空格，已修正。

![image](https://github.com/JiepengLab/notebook/assets/65861390/a9aad6db-8984-4237-ae4c-115586f685ba)

**Comment by JiepengLab** [comment]
### 第七个

>  ![image](https://github.com/JiepengLab/notebook/assets/65861390/be2b5362-701e-4ddf-9010-67d8682808e8)

你说的对，M是在这个方法刚开头的假设给出的。已修正

![image](https://github.com/JiepengLab/notebook/assets/65861390/b65fa106-474f-4fe0-b2f0-b9fe52e4c4c8)

### 第八个

> ![image](https://github.com/JiepengLab/notebook/assets/65861390/89291816-4d3a-4765-bcd6-8929070403f9)

你的表述更准确，已修正。

![image](https://github.com/JiepengLab/notebook/assets/65861390/d7b64964-3c49-487e-aa8d-a956d70aa88f)

### 第九个

> ![image](https://github.com/JiepengLab/notebook/assets/65861390/4cf31f71-3ae9-4b78-9a1c-3f2354c535bb)

遗漏了，已修正

![image](https://github.com/JiepengLab/notebook/assets/65861390/e35bacfe-1eec-4f5d-8b0b-fb7a67f89fd0)

### 第十个

> ![image](https://github.com/JiepengLab/notebook/assets/65861390/df1c6f4a-067c-4349-9c9f-ae943085ae00)

已修正

![image](https://github.com/JiepengLab/notebook/assets/65861390/6492a204-d0c0-41e5-8383-fe05a429f16d)

###  第十一个

>  ![image](https://github.com/JiepengLab/notebook/assets/65861390/27f3367a-23ed-405d-a765-cea580e3a335)

已修正

![image](https://github.com/JiepengLab/notebook/assets/65861390/873eac2f-01f1-49d6-8c39-627eb83d2d21)

### 第十二、十三、十四个

> 渲染与错别字问题

已修正。

**Comment by stormckey** [comment]
好耶！
